### ISSUE TITLE
Identity provider 'live.com' does not exist in tenant 'Adobe' and cannot access the application

### ISSUE THREAD

**Issue by thissayantan** [adobe/helix-onedrive-cli#70]
**Description**
Failed to get access token

**To Reproduce**
1. 1d login
2. click on https://microsoft.com/devicelogin
3. put the code
4. input user name, password

**Expected behavior**
Successful sign-in and receive token

**Screenshots**
I've attached the screenshot

**Version:**
1.5.2

**Additional context**
Request Id: c46de06a-a46f-46e7-a7ec-c5de0c478000
Correlation Id: 60348ad5-9671-49d8-bbb7-7894edba8aee
Timestamp: 2020-08-23T15:02:40Z
Message: AADSTS50020: User account 'this.sayantan@outlook.com' from identity provider 'live.com' does not exist in tenant 'Adobe' and cannot access the application 'f4c79ff7-bbd2-4b36-822e-a89eb6de4578'(Helix OneDrive CLI) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
![login microsoftonline com_common_federation_oauth2](https://user-images.githubusercontent.com/2451056/90981876-af27ec00-e58d-11ea-95bf-48104a320f7f.png)

**Comment by tripodsan** [comment]
due to security restrictions, the default OneDrive Client only works for accounts registered in adobe's AD.

If you want to use the cli, you need to create your own application in azure and set the respective `.env`. eg:

```env
# your applications client id
AZURE_APP_CLIENT_ID="04b07795-8ddb-461a-bbee-02f9e1bf7b46"
```

**Comment by tripodsan** [comment]
won't fix.
