### ISSUE TITLE
New login mode with tokens cache seems to ignore refreshToken

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-onedrive-cli#92]
After a successful `1d login`, I get a valid `.auth.json` in the current working directory, and all operations work as expected. 

After the `accessToken` has expired, though, every further attempt to execute an operation fails with `'Access token has expired.'` So, apparently, the `refreshToken` in `.auth.json` is ignored and another `1d login` is required.

**Comment by dominique-pfister** [comment]
Looking at the calling sequence in detail, `getOneDriveClient` adds the stored tokens to the `AuthorizationContext` cache. It eventually calls `AuthenticationContext.acquireTokenWithClientCredentials`, which finds the item in the cache and returns it **without** looking at the expiration date.

**Comment by tripodsan** [comment]
maybe it should call the 

```
  public acquireToken(resource: string, userId: string, clientId: string, callback: AcquireTokenCallback): void
```

instead. I assume that it will automatically use the refresh token

**Comment by dominique-pfister** [comment]
Where should it take the `userId` parameter from?

**Comment by tripodsan** [comment]
> Where should the `userId` parameter come from, e.g. when the login is done without username/password?

well, you always have a userid. when obtaining a refresh token, the repsective userid is also stored in the cache.
