### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by capriciousduck** [adobe/helix-onedrive-cli#94]
When I execute `1d login` I get the following error.

`[ERROR] Error while refreshing access token Error: The clientSecret parameter is required.
    at Object.validateStringParameter (/usr/lib/node_modules/@adobe/helix-onedrive-cli/node_modules/adal-node/lib/argument.js:37:13)
    at AuthenticationContext.acquireTokenWithClientCredentials (/usr/lib/node_modules/@adobe/helix-onedrive-cli/node_modules/adal-node/lib/authentication-context.js:282:14)
    at /usr/lib/node_modules/@adobe/helix-onedrive-cli/node_modules/@adobe/helix-onedrive-support/src/OneDrive.js:170:17
    at new Promise (<anonymous>)
    at OneDrive.getAccessToken (/usr/lib/node_modules/@adobe/helix-onedrive-cli/node_modules/@adobe/helix-onedrive-support/src/OneDrive.js:148:12)
    at Object.login (/usr/lib/node_modules/@adobe/helix-onedrive-cli/src/onedrive.js:47:34)
The clientSecret parameter is required.`

**Comment by dominique-pfister** [comment]
You need to specify an `AZURE_APP_CLIENT_SECRET` environment variable, either in your shell or in an `.env` file. More information is available in the [Setup](https://github.com/adobe/helix-onedrive-cli#setup) section.

**Comment by capriciousduck** [comment]
Ok, but how I generate a client ID and client secret?

**Comment by capriciousduck** [comment]
PS: Is it not possible to go with default settings?

You said, "The 1d client runs with a default client id which supports interactive login". Now, why do I need an env variable?

**Comment by capriciousduck** [comment]
And what node version do you recommend?

**Comment by dominique-pfister** [comment]
> Ok, but how I generate a client ID and client secret?
This is described here: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/msa-oauth?view=odsp-graph-online

> You said, "The 1d client runs with a default client id which supports interactive login". Now, why do I need an env variable?
The default client id belongs to an app we registered ourselves. I'm afraid, that part of the documentation suggests that it can be re-used while it is actually confined to our services. We'll review that part of the documentation.

> And what node version do you recommend?
In our development we're using node v10.

**Comment by capriciousduck** [comment]
Ok. Will check and post the results. Moreover, can I use node v14?

**Comment by capriciousduck** [comment]
I installed the app using NPM and what do URL do I set as "Redirect URL" in the Azure Portal? And what platform should I use, the Web Applications or Mobile and Desktop Applications?

I am talking about this one here

![image](https://user-images.githubusercontent.com/37048515/99145286-877b8800-2693-11eb-9479-5ef6f7c9b3d8.png)

**Comment by tripodsan** [comment]
@capriciousduck we fixed some issues with the default client id. the new version should allow you now to login using the device code. the default client id is the one from Microsoft's ADAL client. so if you just do:

````
1d login
```

your browser should open and you should see something like the following after your entered the device code:

![image](https://user-images.githubusercontent.com/917628/99206510-eb6e8f80-27fe-11eb-8b05-959aa0d27bab.png)

after that, you should be logged in.
