### ISSUE TITLE
Login requires a client secret, even when doing a login with username/password

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-onedrive-cli#95]
The code in login:

https://github.com/adobe/helix-onedrive-cli/blob/7778ebae2983bfa4a8a685f1aad8c4f542e4d8e6/src/onedrive.js#L45-L51

tries to obtain an access token via client id and secret **even** when username/password have been passed on the command line. 

`OneDrive.getAccessToken` ends up calling `AuthenticationContext.acquireTokenWithClientCredentials`, which expects a non-empty client secret. Thus, even when invoking the client as:
```
$ node . login -u <username>
```
an error is thrown, complaining about a missing client secret. This seems related to #94

**Comment by tripodsan** [comment]
the following now works:


### device code login
```
$ rm .auth.json
$ 1d login
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code HER6N5E4P to authenticate.
Logged in as: Example User (test@example.com)
```

### ROPC login
```
$ rm .auth.json
$ 1d login -u test@example.com
username: test@example.com
password: ***
Logged in as: Example User (test@example.com)
```

### re-login
```
$ 1d login
already logged in.
```

### retrieving _me_
```
$ 1d me
Logged in as: Example User (test@example.com)
```
